### PR TITLE
add a gulp server task and fix path for minified css file

### PR DESCRIPTION
**Pull request by frankinedinburgh**
added a task to easily get this app up and running in the browser

### CODE REVIEW

**Comment by ryuhhnn** [comment]
Do you think it would be better to remove the "host" property so that it will just run at localhost instead of 0.0.0.0?

**Comment by frankinedinburgh** [comment]
Hi Ryuhhn, I originally thought it would be good to use gulp task to set up server but now I'm thinking of changing it to express js. I will update this commit for you to review and I will use 
127.0.0.0:8888 as opposed to 0.0.0.0

**Comment by agauniyal** [comment]
I should've used browsersync for these tasks, launches a server in specified directory providing a localhost address as well as a localtunnel subdomain eg. wireframe.localtunnel.me and maintains sync b/w different devices.

Sorry I'm busy these days, @ryuhhnn could take a look at PRs based on his availability 😄

**Comment by ryuhhnn** [comment]
I second using express.js! Once you make those fixes I'll merge :)

**Pull request closed without merging**
